//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Addresses struct {
	ID         string `sql:"primary_key"`
	ContactID  string
	Street     *string
	City       *string
	Province   *string
	PostalCode *string
	Country    *string
	CreatedAt  int64
	UpdatedAt  int64
}
