//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Items struct {
	ID        uint64 `sql:"primary_key"`
	Name      string
	Sku       string
	Currency  string
	Stock     int32
	CreatedAt *time.Time
	UpdatedAt *time.Time
}
