//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Addresses = newAddressesTable("db", "addresses", "")

type addressesTable struct {
	mysql.Table

	// Columns
	ID         mysql.ColumnString
	ContactID  mysql.ColumnString
	Street     mysql.ColumnString
	City       mysql.ColumnString
	Province   mysql.ColumnString
	PostalCode mysql.ColumnString
	Country    mysql.ColumnString
	CreatedAt  mysql.ColumnInteger
	UpdatedAt  mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type AddressesTable struct {
	addressesTable

	NEW addressesTable
}

// AS creates new AddressesTable with assigned alias
func (a AddressesTable) AS(alias string) *AddressesTable {
	return newAddressesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AddressesTable with assigned schema name
func (a AddressesTable) FromSchema(schemaName string) *AddressesTable {
	return newAddressesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AddressesTable with assigned table prefix
func (a AddressesTable) WithPrefix(prefix string) *AddressesTable {
	return newAddressesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AddressesTable with assigned table suffix
func (a AddressesTable) WithSuffix(suffix string) *AddressesTable {
	return newAddressesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAddressesTable(schemaName, tableName, alias string) *AddressesTable {
	return &AddressesTable{
		addressesTable: newAddressesTableImpl(schemaName, tableName, alias),
		NEW:            newAddressesTableImpl("", "new", ""),
	}
}

func newAddressesTableImpl(schemaName, tableName, alias string) addressesTable {
	var (
		IDColumn         = mysql.StringColumn("id")
		ContactIDColumn  = mysql.StringColumn("contact_id")
		StreetColumn     = mysql.StringColumn("street")
		CityColumn       = mysql.StringColumn("city")
		ProvinceColumn   = mysql.StringColumn("province")
		PostalCodeColumn = mysql.StringColumn("postal_code")
		CountryColumn    = mysql.StringColumn("country")
		CreatedAtColumn  = mysql.IntegerColumn("created_at")
		UpdatedAtColumn  = mysql.IntegerColumn("updated_at")
		allColumns       = mysql.ColumnList{IDColumn, ContactIDColumn, StreetColumn, CityColumn, ProvinceColumn, PostalCodeColumn, CountryColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = mysql.ColumnList{ContactIDColumn, StreetColumn, CityColumn, ProvinceColumn, PostalCodeColumn, CountryColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns   = mysql.ColumnList{}
	)

	return addressesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		ContactID:  ContactIDColumn,
		Street:     StreetColumn,
		City:       CityColumn,
		Province:   ProvinceColumn,
		PostalCode: PostalCodeColumn,
		Country:    CountryColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
