//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Contacts = newContactsTable("db", "contacts", "")

type contactsTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnString
	FirstName mysql.ColumnString
	LastName  mysql.ColumnString
	Email     mysql.ColumnString
	Phone     mysql.ColumnString
	UserID    mysql.ColumnString
	CreatedAt mysql.ColumnInteger
	UpdatedAt mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type ContactsTable struct {
	contactsTable

	NEW contactsTable
}

// AS creates new ContactsTable with assigned alias
func (a ContactsTable) AS(alias string) *ContactsTable {
	return newContactsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ContactsTable with assigned schema name
func (a ContactsTable) FromSchema(schemaName string) *ContactsTable {
	return newContactsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ContactsTable with assigned table prefix
func (a ContactsTable) WithPrefix(prefix string) *ContactsTable {
	return newContactsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ContactsTable with assigned table suffix
func (a ContactsTable) WithSuffix(suffix string) *ContactsTable {
	return newContactsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newContactsTable(schemaName, tableName, alias string) *ContactsTable {
	return &ContactsTable{
		contactsTable: newContactsTableImpl(schemaName, tableName, alias),
		NEW:           newContactsTableImpl("", "new", ""),
	}
}

func newContactsTableImpl(schemaName, tableName, alias string) contactsTable {
	var (
		IDColumn        = mysql.StringColumn("id")
		FirstNameColumn = mysql.StringColumn("first_name")
		LastNameColumn  = mysql.StringColumn("last_name")
		EmailColumn     = mysql.StringColumn("email")
		PhoneColumn     = mysql.StringColumn("phone")
		UserIDColumn    = mysql.StringColumn("user_id")
		CreatedAtColumn = mysql.IntegerColumn("created_at")
		UpdatedAtColumn = mysql.IntegerColumn("updated_at")
		allColumns      = mysql.ColumnList{IDColumn, FirstNameColumn, LastNameColumn, EmailColumn, PhoneColumn, UserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = mysql.ColumnList{FirstNameColumn, LastNameColumn, EmailColumn, PhoneColumn, UserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = mysql.ColumnList{}
	)

	return contactsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		FirstName: FirstNameColumn,
		LastName:  LastNameColumn,
		Email:     EmailColumn,
		Phone:     PhoneColumn,
		UserID:    UserIDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
