// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AddressesColumns holds the columns for the "addresses" table.
	AddressesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 36},
		{Name: "street", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "city", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "province", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "postal_code", Type: field.TypeString, Nullable: true, Size: 10},
		{Name: "country", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "contact_id", Type: field.TypeString, Size: 36},
	}
	// AddressesTable holds the schema information for the "addresses" table.
	AddressesTable = &schema.Table{
		Name:       "addresses",
		Columns:    AddressesColumns,
		PrimaryKey: []*schema.Column{AddressesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "addresses_contacts_addresses",
				Columns:    []*schema.Column{AddressesColumns[8]},
				RefColumns: []*schema.Column{ContactsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ContactsColumns holds the columns for the "contacts" table.
	ContactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 36},
		{Name: "first_name", Type: field.TypeString, Size: 100},
		{Name: "last_name", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "email", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "phone", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeString, Size: 36},
	}
	// ContactsTable holds the schema information for the "contacts" table.
	ContactsTable = &schema.Table{
		Name:       "contacts",
		Columns:    ContactsColumns,
		PrimaryKey: []*schema.Column{ContactsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "contacts_users_contacts",
				Columns:    []*schema.Column{ContactsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "sku", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "currency", Type: field.TypeString, Size: 10},
		{Name: "stock", Type: field.TypeInt32},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 36},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "password", Type: field.TypeString, Size: 100},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AddressesTable,
		ContactsTable,
		ItemsTable,
		UsersTable,
	}
)

func init() {
	AddressesTable.ForeignKeys[0].RefTable = ContactsTable
	ContactsTable.ForeignKeys[0].RefTable = UsersTable
}
