// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"golang-clean-architecture/ent/address"
	"golang-clean-architecture/ent/contact"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Address is the model entity for the Address schema.
type Address struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ContactID holds the value of the "contact_id" field.
	ContactID string `json:"contact_id,omitempty"`
	// Street holds the value of the "street" field.
	Street *string `json:"street,omitempty"`
	// City holds the value of the "city" field.
	City *string `json:"city,omitempty"`
	// Province holds the value of the "province" field.
	Province *string `json:"province,omitempty"`
	// PostalCode holds the value of the "postal_code" field.
	PostalCode *string `json:"postal_code,omitempty"`
	// Country holds the value of the "country" field.
	Country *string `json:"country,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AddressQuery when eager-loading is set.
	Edges        AddressEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AddressEdges holds the relations/edges for other nodes in the graph.
type AddressEdges struct {
	// Contact holds the value of the contact edge.
	Contact *Contact `json:"contact,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ContactOrErr returns the Contact value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AddressEdges) ContactOrErr() (*Contact, error) {
	if e.Contact != nil {
		return e.Contact, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: contact.Label}
	}
	return nil, &NotLoadedError{edge: "contact"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Address) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case address.FieldCreatedAt, address.FieldUpdatedAt:
			values[i] = new(sql.NullInt64)
		case address.FieldID, address.FieldContactID, address.FieldStreet, address.FieldCity, address.FieldProvince, address.FieldPostalCode, address.FieldCountry:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Address fields.
func (_m *Address) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case address.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case address.FieldContactID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_id", values[i])
			} else if value.Valid {
				_m.ContactID = value.String
			}
		case address.FieldStreet:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field street", values[i])
			} else if value.Valid {
				_m.Street = new(string)
				*_m.Street = value.String
			}
		case address.FieldCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field city", values[i])
			} else if value.Valid {
				_m.City = new(string)
				*_m.City = value.String
			}
		case address.FieldProvince:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field province", values[i])
			} else if value.Valid {
				_m.Province = new(string)
				*_m.Province = value.String
			}
		case address.FieldPostalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field postal_code", values[i])
			} else if value.Valid {
				_m.PostalCode = new(string)
				*_m.PostalCode = value.String
			}
		case address.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = new(string)
				*_m.Country = value.String
			}
		case address.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case address.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Address.
// This includes values selected through modifiers, order, etc.
func (_m *Address) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryContact queries the "contact" edge of the Address entity.
func (_m *Address) QueryContact() *ContactQuery {
	return NewAddressClient(_m.config).QueryContact(_m)
}

// Update returns a builder for updating this Address.
// Note that you need to call Address.Unwrap() before calling this method if this Address
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Address) Update() *AddressUpdateOne {
	return NewAddressClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Address entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Address) Unwrap() *Address {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Address is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Address) String() string {
	var builder strings.Builder
	builder.WriteString("Address(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("contact_id=")
	builder.WriteString(_m.ContactID)
	builder.WriteString(", ")
	if v := _m.Street; v != nil {
		builder.WriteString("street=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.City; v != nil {
		builder.WriteString("city=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Province; v != nil {
		builder.WriteString("province=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PostalCode; v != nil {
		builder.WriteString("postal_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Country; v != nil {
		builder.WriteString("country=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteByte(')')
	return builder.String()
}

// Addresses is a parsable slice of Address.
type Addresses []*Address
