// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-clean-architecture/ent/address"
	"golang-clean-architecture/ent/contact"
	"golang-clean-architecture/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContactID sets the "contact_id" field.
func (_u *AddressUpdate) SetContactID(v string) *AddressUpdate {
	_u.mutation.SetContactID(v)
	return _u
}

// SetNillableContactID sets the "contact_id" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableContactID(v *string) *AddressUpdate {
	if v != nil {
		_u.SetContactID(*v)
	}
	return _u
}

// SetStreet sets the "street" field.
func (_u *AddressUpdate) SetStreet(v string) *AddressUpdate {
	_u.mutation.SetStreet(v)
	return _u
}

// SetNillableStreet sets the "street" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableStreet(v *string) *AddressUpdate {
	if v != nil {
		_u.SetStreet(*v)
	}
	return _u
}

// ClearStreet clears the value of the "street" field.
func (_u *AddressUpdate) ClearStreet() *AddressUpdate {
	_u.mutation.ClearStreet()
	return _u
}

// SetCity sets the "city" field.
func (_u *AddressUpdate) SetCity(v string) *AddressUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableCity(v *string) *AddressUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *AddressUpdate) ClearCity() *AddressUpdate {
	_u.mutation.ClearCity()
	return _u
}

// SetProvince sets the "province" field.
func (_u *AddressUpdate) SetProvince(v string) *AddressUpdate {
	_u.mutation.SetProvince(v)
	return _u
}

// SetNillableProvince sets the "province" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableProvince(v *string) *AddressUpdate {
	if v != nil {
		_u.SetProvince(*v)
	}
	return _u
}

// ClearProvince clears the value of the "province" field.
func (_u *AddressUpdate) ClearProvince() *AddressUpdate {
	_u.mutation.ClearProvince()
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *AddressUpdate) SetPostalCode(v string) *AddressUpdate {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *AddressUpdate) SetNillablePostalCode(v *string) *AddressUpdate {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// ClearPostalCode clears the value of the "postal_code" field.
func (_u *AddressUpdate) ClearPostalCode() *AddressUpdate {
	_u.mutation.ClearPostalCode()
	return _u
}

// SetCountry sets the "country" field.
func (_u *AddressUpdate) SetCountry(v string) *AddressUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableCountry(v *string) *AddressUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *AddressUpdate) ClearCountry() *AddressUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AddressUpdate) SetCreatedAt(v int64) *AddressUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableCreatedAt(v *int64) *AddressUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *AddressUpdate) AddCreatedAt(v int64) *AddressUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddressUpdate) SetUpdatedAt(v int64) *AddressUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableUpdatedAt(v *int64) *AddressUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *AddressUpdate) AddUpdatedAt(v int64) *AddressUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetContact sets the "contact" edge to the Contact entity.
func (_u *AddressUpdate) SetContact(v *Contact) *AddressUpdate {
	return _u.SetContactID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdate) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearContact clears the "contact" edge to the Contact entity.
func (_u *AddressUpdate) ClearContact() *AddressUpdate {
	_u.mutation.ClearContact()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AddressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AddressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdate) check() error {
	if v, ok := _u.mutation.ContactID(); ok {
		if err := address.ContactIDValidator(v); err != nil {
			return &ValidationError{Name: "contact_id", err: fmt.Errorf(`ent: validator failed for field "Address.contact_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Street(); ok {
		if err := address.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "Address.street": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := address.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Address.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Province(); ok {
		if err := address.ProvinceValidator(v); err != nil {
			return &ValidationError{Name: "province", err: fmt.Errorf(`ent: validator failed for field "Address.province": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PostalCode(); ok {
		if err := address.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`ent: validator failed for field "Address.postal_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := address.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Address.country": %w`, err)}
		}
	}
	if _u.mutation.ContactCleared() && len(_u.mutation.ContactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.contact"`)
	}
	return nil
}

func (_u *AddressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Street(); ok {
		_spec.SetField(address.FieldStreet, field.TypeString, value)
	}
	if _u.mutation.StreetCleared() {
		_spec.ClearField(address.FieldStreet, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(address.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Province(); ok {
		_spec.SetField(address.FieldProvince, field.TypeString, value)
	}
	if _u.mutation.ProvinceCleared() {
		_spec.ClearField(address.FieldProvince, field.TypeString)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(address.FieldPostalCode, field.TypeString, value)
	}
	if _u.mutation.PostalCodeCleared() {
		_spec.ClearField(address.FieldPostalCode, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(address.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(address.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(address.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(address.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(address.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(address.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.ContactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.ContactTable,
			Columns: []string{address.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.ContactTable,
			Columns: []string{address.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetContactID sets the "contact_id" field.
func (_u *AddressUpdateOne) SetContactID(v string) *AddressUpdateOne {
	_u.mutation.SetContactID(v)
	return _u
}

// SetNillableContactID sets the "contact_id" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableContactID(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetContactID(*v)
	}
	return _u
}

// SetStreet sets the "street" field.
func (_u *AddressUpdateOne) SetStreet(v string) *AddressUpdateOne {
	_u.mutation.SetStreet(v)
	return _u
}

// SetNillableStreet sets the "street" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableStreet(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetStreet(*v)
	}
	return _u
}

// ClearStreet clears the value of the "street" field.
func (_u *AddressUpdateOne) ClearStreet() *AddressUpdateOne {
	_u.mutation.ClearStreet()
	return _u
}

// SetCity sets the "city" field.
func (_u *AddressUpdateOne) SetCity(v string) *AddressUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableCity(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *AddressUpdateOne) ClearCity() *AddressUpdateOne {
	_u.mutation.ClearCity()
	return _u
}

// SetProvince sets the "province" field.
func (_u *AddressUpdateOne) SetProvince(v string) *AddressUpdateOne {
	_u.mutation.SetProvince(v)
	return _u
}

// SetNillableProvince sets the "province" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableProvince(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetProvince(*v)
	}
	return _u
}

// ClearProvince clears the value of the "province" field.
func (_u *AddressUpdateOne) ClearProvince() *AddressUpdateOne {
	_u.mutation.ClearProvince()
	return _u
}

// SetPostalCode sets the "postal_code" field.
func (_u *AddressUpdateOne) SetPostalCode(v string) *AddressUpdateOne {
	_u.mutation.SetPostalCode(v)
	return _u
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillablePostalCode(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetPostalCode(*v)
	}
	return _u
}

// ClearPostalCode clears the value of the "postal_code" field.
func (_u *AddressUpdateOne) ClearPostalCode() *AddressUpdateOne {
	_u.mutation.ClearPostalCode()
	return _u
}

// SetCountry sets the "country" field.
func (_u *AddressUpdateOne) SetCountry(v string) *AddressUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableCountry(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *AddressUpdateOne) ClearCountry() *AddressUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AddressUpdateOne) SetCreatedAt(v int64) *AddressUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableCreatedAt(v *int64) *AddressUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *AddressUpdateOne) AddCreatedAt(v int64) *AddressUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AddressUpdateOne) SetUpdatedAt(v int64) *AddressUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableUpdatedAt(v *int64) *AddressUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *AddressUpdateOne) AddUpdatedAt(v int64) *AddressUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetContact sets the "contact" edge to the Contact entity.
func (_u *AddressUpdateOne) SetContact(v *Contact) *AddressUpdateOne {
	return _u.SetContactID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdateOne) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearContact clears the "contact" edge to the Contact entity.
func (_u *AddressUpdateOne) ClearContact() *AddressUpdateOne {
	_u.mutation.ClearContact()
	return _u
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Address entity.
func (_u *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdateOne) check() error {
	if v, ok := _u.mutation.ContactID(); ok {
		if err := address.ContactIDValidator(v); err != nil {
			return &ValidationError{Name: "contact_id", err: fmt.Errorf(`ent: validator failed for field "Address.contact_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Street(); ok {
		if err := address.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "Address.street": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := address.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Address.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Province(); ok {
		if err := address.ProvinceValidator(v); err != nil {
			return &ValidationError{Name: "province", err: fmt.Errorf(`ent: validator failed for field "Address.province": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PostalCode(); ok {
		if err := address.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`ent: validator failed for field "Address.postal_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := address.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Address.country": %w`, err)}
		}
	}
	if _u.mutation.ContactCleared() && len(_u.mutation.ContactIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Address.contact"`)
	}
	return nil
}

func (_u *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(address.Table, address.Columns, sqlgraph.NewFieldSpec(address.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, address.FieldID)
		for _, f := range fields {
			if !address.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != address.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Street(); ok {
		_spec.SetField(address.FieldStreet, field.TypeString, value)
	}
	if _u.mutation.StreetCleared() {
		_spec.ClearField(address.FieldStreet, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(address.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(address.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Province(); ok {
		_spec.SetField(address.FieldProvince, field.TypeString, value)
	}
	if _u.mutation.ProvinceCleared() {
		_spec.ClearField(address.FieldProvince, field.TypeString)
	}
	if value, ok := _u.mutation.PostalCode(); ok {
		_spec.SetField(address.FieldPostalCode, field.TypeString, value)
	}
	if _u.mutation.PostalCodeCleared() {
		_spec.ClearField(address.FieldPostalCode, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(address.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(address.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(address.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(address.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(address.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(address.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.ContactCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.ContactTable,
			Columns: []string{address.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.ContactTable,
			Columns: []string{address.ContactColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{address.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
