// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"golang-clean-architecture/ent/item"
	"golang-clean-architecture/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ItemUpdate is the builder for updating Item entities.
type ItemUpdate struct {
	config
	hooks    []Hook
	mutation *ItemMutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (_u *ItemUpdate) Where(ps ...predicate.Item) *ItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ItemUpdate) SetName(v string) *ItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableName(v *string) *ItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSku sets the "sku" field.
func (_u *ItemUpdate) SetSku(v string) *ItemUpdate {
	_u.mutation.SetSku(v)
	return _u
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableSku(v *string) *ItemUpdate {
	if v != nil {
		_u.SetSku(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ItemUpdate) SetCurrency(v string) *ItemUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableCurrency(v *string) *ItemUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStock sets the "stock" field.
func (_u *ItemUpdate) SetStock(v int32) *ItemUpdate {
	_u.mutation.ResetStock()
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableStock(v *int32) *ItemUpdate {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// AddStock adds value to the "stock" field.
func (_u *ItemUpdate) AddStock(v int32) *ItemUpdate {
	_u.mutation.AddStock(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ItemUpdate) SetCreatedAt(v time.Time) *ItemUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableCreatedAt(v *time.Time) *ItemUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ItemUpdate) SetUpdatedAt(v time.Time) *ItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ItemMutation object of the builder.
func (_u *ItemUpdate) Mutation() *ItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := item.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := item.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Item.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sku(); ok {
		if err := item.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Item.sku": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := item.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Item.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *ItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sku(); ok {
		_spec.SetField(item.FieldSku, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(item.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(item.FieldStock, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStock(); ok {
		_spec.AddField(item.FieldStock, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(item.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(item.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ItemUpdateOne is the builder for updating a single Item entity.
type ItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemMutation
}

// SetName sets the "name" field.
func (_u *ItemUpdateOne) SetName(v string) *ItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableName(v *string) *ItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSku sets the "sku" field.
func (_u *ItemUpdateOne) SetSku(v string) *ItemUpdateOne {
	_u.mutation.SetSku(v)
	return _u
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableSku(v *string) *ItemUpdateOne {
	if v != nil {
		_u.SetSku(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ItemUpdateOne) SetCurrency(v string) *ItemUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableCurrency(v *string) *ItemUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStock sets the "stock" field.
func (_u *ItemUpdateOne) SetStock(v int32) *ItemUpdateOne {
	_u.mutation.ResetStock()
	_u.mutation.SetStock(v)
	return _u
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableStock(v *int32) *ItemUpdateOne {
	if v != nil {
		_u.SetStock(*v)
	}
	return _u
}

// AddStock adds value to the "stock" field.
func (_u *ItemUpdateOne) AddStock(v int32) *ItemUpdateOne {
	_u.mutation.AddStock(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ItemUpdateOne) SetCreatedAt(v time.Time) *ItemUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableCreatedAt(v *time.Time) *ItemUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ItemUpdateOne) SetUpdatedAt(v time.Time) *ItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ItemMutation object of the builder.
func (_u *ItemUpdateOne) Mutation() *ItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (_u *ItemUpdateOne) Where(ps ...predicate.Item) *ItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ItemUpdateOne) Select(field string, fields ...string) *ItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Item entity.
func (_u *ItemUpdateOne) Save(ctx context.Context) (*Item, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemUpdateOne) SaveX(ctx context.Context) *Item {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := item.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := item.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Item.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sku(); ok {
		if err := item.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Item.sku": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := item.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Item.currency": %w`, err)}
		}
	}
	return nil
}

func (_u *ItemUpdateOne) sqlSave(ctx context.Context) (_node *Item, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Item.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, item.FieldID)
		for _, f := range fields {
			if !item.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != item.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sku(); ok {
		_spec.SetField(item.FieldSku, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(item.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stock(); ok {
		_spec.SetField(item.FieldStock, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStock(); ok {
		_spec.AddField(item.FieldStock, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(item.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(item.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Item{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
