// Code generated by ent, DO NOT EDIT.

package ent

import (
	"golang-clean-architecture/ent/address"
	"golang-clean-architecture/ent/contact"
	"golang-clean-architecture/ent/item"
	"golang-clean-architecture/ent/schema"
	"golang-clean-architecture/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	addressFields := schema.Address{}.Fields()
	_ = addressFields
	// addressDescContactID is the schema descriptor for contact_id field.
	addressDescContactID := addressFields[1].Descriptor()
	// address.ContactIDValidator is a validator for the "contact_id" field. It is called by the builders before save.
	address.ContactIDValidator = func() func(string) error {
		validators := addressDescContactID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(contact string) error {
			for _, fn := range fns {
				if err := fn(contact); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// addressDescStreet is the schema descriptor for street field.
	addressDescStreet := addressFields[2].Descriptor()
	// address.StreetValidator is a validator for the "street" field. It is called by the builders before save.
	address.StreetValidator = addressDescStreet.Validators[0].(func(string) error)
	// addressDescCity is the schema descriptor for city field.
	addressDescCity := addressFields[3].Descriptor()
	// address.CityValidator is a validator for the "city" field. It is called by the builders before save.
	address.CityValidator = addressDescCity.Validators[0].(func(string) error)
	// addressDescProvince is the schema descriptor for province field.
	addressDescProvince := addressFields[4].Descriptor()
	// address.ProvinceValidator is a validator for the "province" field. It is called by the builders before save.
	address.ProvinceValidator = addressDescProvince.Validators[0].(func(string) error)
	// addressDescPostalCode is the schema descriptor for postal_code field.
	addressDescPostalCode := addressFields[5].Descriptor()
	// address.PostalCodeValidator is a validator for the "postal_code" field. It is called by the builders before save.
	address.PostalCodeValidator = addressDescPostalCode.Validators[0].(func(string) error)
	// addressDescCountry is the schema descriptor for country field.
	addressDescCountry := addressFields[6].Descriptor()
	// address.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	address.CountryValidator = addressDescCountry.Validators[0].(func(string) error)
	// addressDescID is the schema descriptor for id field.
	addressDescID := addressFields[0].Descriptor()
	// address.IDValidator is a validator for the "id" field. It is called by the builders before save.
	address.IDValidator = func() func(string) error {
		validators := addressDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	contactFields := schema.Contact{}.Fields()
	_ = contactFields
	// contactDescFirstName is the schema descriptor for first_name field.
	contactDescFirstName := contactFields[1].Descriptor()
	// contact.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	contact.FirstNameValidator = func() func(string) error {
		validators := contactDescFirstName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(first_name string) error {
			for _, fn := range fns {
				if err := fn(first_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// contactDescLastName is the schema descriptor for last_name field.
	contactDescLastName := contactFields[2].Descriptor()
	// contact.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	contact.LastNameValidator = contactDescLastName.Validators[0].(func(string) error)
	// contactDescEmail is the schema descriptor for email field.
	contactDescEmail := contactFields[3].Descriptor()
	// contact.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	contact.EmailValidator = contactDescEmail.Validators[0].(func(string) error)
	// contactDescPhone is the schema descriptor for phone field.
	contactDescPhone := contactFields[4].Descriptor()
	// contact.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	contact.PhoneValidator = contactDescPhone.Validators[0].(func(string) error)
	// contactDescUserID is the schema descriptor for user_id field.
	contactDescUserID := contactFields[5].Descriptor()
	// contact.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	contact.UserIDValidator = func() func(string) error {
		validators := contactDescUserID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(user string) error {
			for _, fn := range fns {
				if err := fn(user); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// contactDescID is the schema descriptor for id field.
	contactDescID := contactFields[0].Descriptor()
	// contact.IDValidator is a validator for the "id" field. It is called by the builders before save.
	contact.IDValidator = func() func(string) error {
		validators := contactDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescName is the schema descriptor for name field.
	itemDescName := itemFields[0].Descriptor()
	// item.NameValidator is a validator for the "name" field. It is called by the builders before save.
	item.NameValidator = func() func(string) error {
		validators := itemDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemDescSku is the schema descriptor for sku field.
	itemDescSku := itemFields[1].Descriptor()
	// item.SkuValidator is a validator for the "sku" field. It is called by the builders before save.
	item.SkuValidator = func() func(string) error {
		validators := itemDescSku.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(sku string) error {
			for _, fn := range fns {
				if err := fn(sku); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemDescCurrency is the schema descriptor for currency field.
	itemDescCurrency := itemFields[2].Descriptor()
	// item.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	item.CurrencyValidator = func() func(string) error {
		validators := itemDescCurrency.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(currency string) error {
			for _, fn := range fns {
				if err := fn(currency); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// itemDescCreatedAt is the schema descriptor for created_at field.
	itemDescCreatedAt := itemFields[4].Descriptor()
	// item.DefaultCreatedAt holds the default value on creation for the created_at field.
	item.DefaultCreatedAt = itemDescCreatedAt.Default.(func() time.Time)
	// itemDescUpdatedAt is the schema descriptor for updated_at field.
	itemDescUpdatedAt := itemFields[5].Descriptor()
	// item.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	item.DefaultUpdatedAt = itemDescUpdatedAt.Default.(func() time.Time)
	// item.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	item.UpdateDefaultUpdatedAt = itemDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = func() func(string) error {
		validators := userDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password string) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = func() func(string) error {
		validators := userDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
