// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Address is the predicate function for address builders.
type Address func(*sql.Selector)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
